version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: adamplansky-file-downloader_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/adamplansky/umbrel-apps:latest
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /home/umbrel/umbrel/home/Downloads/media:/downloads
    environment:
      - TZ=${TZ}
      - WEBSHARE_USERNAME=${WEBSHARE_USERNAME:-}
      - WEBSHARE_PASSWORD=${WEBSHARE_PASSWORD:-}
      - WEBSHARE_WST=${WEBSHARE_WST:-}
      - TMDB_ACCESS_TOKEN=${TMDB_ACCESS_TOKEN:-}
      - TMDB_API_KEY=${TMDB_API_KEY:-}
      - MAX_CONCURRENT_DOWNLOADS=${MAX_CONCURRENT_DOWNLOADS:-5}
      - SERIES_SEARCH_CONCURRENCY=${SERIES_SEARCH_CONCURRENCY:-5}
